name: Publish JAR to GitHub Releases

on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Java 21 or the version you're using
          distribution: 'adopt'
          cache: 'gradle' # Adjust if you're using Maven

      - name: Build JAR (Linux)
        run: ./gradlew build # Adjust the build command for your project

      - name: Publish Release (Linux)
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-linux
          release_name: Release ${{ github.run_number }} (Linux)

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Java 21 or the version you're using
          distribution: 'adopt'

      - name: Build JAR (Windows)
        run: gradlew.bat build # Adjust the build command for your project

      - name: Publish Release (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: build\libs\*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-windows
          release_name: Release ${{ github.run_number }} (Windows)
