name: Publish JAR to GitHub Releases

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Java 17 or the version you're using
          distribution: 'adopt'
          cache: 'maven' # Adjust cache for Maven

      - name: Build JAR (Linux)
        run: mvn package # Adjust the build command for Maven

      - name: Publish Release (Linux)
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-linux
          release_name: Release ${{ github.run_number }} (Linux)

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Java 17 or the version you're using
          distribution: 'adopt'

      - name: Build JAR (Windows)
        run: mvn package # Adjust the build command for Maven

      - name: Publish Release (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-windows
          release_name: Release ${{ github.run_number }} (Windows)
