name: Build and Release

on: workflow_dispatch

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Use the required Java version
          distribution: 'adopt'
          cache: 'maven'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: yb-workload-sim
          path: target/yb-workload-sim.jar

  build-windows:
    runs-on: windows-latest
    needs: build-jar
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim
          path: .

      - name: Package Windows executable
        run: |
          mkdir windows
          echo @echo off > windows/run.bat
          echo java -jar yb-workload-sim.jar >> windows/run.bat

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: yb-workload-sim-windows
          path: windows/

  build-linux:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim
          path: .

      - name: Package Linux executable
        run: |
          mkdir linux
          echo '#!/bin/bash' > linux/run.sh
          echo java -jar yb-workload-sim.jar >> linux/run.sh
          chmod +x linux/run.sh

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: yb-workload-sim-linux
          path: linux/

  build-macos:
    runs-on: macos-latest
    needs: build-jar
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim
          path: .

      - name: Package MacOS executable
        run: |
          mkdir macos
          echo '#!/bin/bash' > macos/run.sh
          echo java -jar yb-workload-sim.jar >> macos/run.sh
          chmod +x macos/run.sh

      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: yb-workload-sim-macos
          path: macos/

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim-windows
          path: ./windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim-linux
          path: ./linux

      - name: Download MacOS artifact
        uses: actions/download-artifact@v3
        with:
          name: yb-workload-sim-macos
          path: ./macos

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./windows/run.bat
          asset_name: yb-workload-sim-windows.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./linux/run.sh
          asset_name: yb-workload-sim-linux.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./macos/run.sh
          asset_name: yb-workload-sim-macos.zip
          asset_content_type: application/zip
